[package]
name = "server"
version = "0.1.0"
edition.workspace = true

[dependencies]
shortener.workspace = true
storage.workspace= true
#
# External dependecies
#
tokio.workspace = true
axum.workspace = true
