[package]
name = "storage"
version = "0.1.0"
edition.workspace = true

[dependencies]
common.workspace = true
#
# External dependencies
#
strum.workspace = true
lazy_static.workspace = true
serde.workspace = true
strum_macros.workspace = true
anyhow.workspace = true
paste = "1.0.15"